###
POST http://localhost:8092/api/v1/auth/authenticate
Content-Type: application/json

{
  "email": "12@mail.com",
  "password": "12укеукук3"
}


###
POST http://localhost:8092/api/v1/auth/register
Content-Type: application/json

{
  "username": "1111111",
  "email": "12@mail.com",
  "password": "12укеукук3",
  "role": "USER"
}
